### ISSUE TITLE
Fatal error Media class does't found

### ISSUE THREAD

**Issue by sudipta26889** [madergrafisch/kirby-plugins#1]
Where can i get the Media class.
whenever i am trying to use the same i got the following error.
FatalErrorException in ImageConverter.php line 35:
Class 'Media' not found

**Comment by seehat** [comment]
It's included in the kirby toolkit (https://github.com/getkirby/toolkit), or when using this as plugin in a kirby cms install (https://github.com/getkirby/starterkit).
